### ISSUE TITLE
homework_1 CR

### ISSUE THREAD

**Issue by Exevald** [CopyTwice/Web-Labs#1]
# CR homework #1

### Общее

Ты забыл закинуть в репозиторий папку с картинками, поэтому сейчас отображается вот так)

![Image](https://github.com/user-attachments/assets/ee25776e-7aa8-445a-9708-01baa54dd2fa)

### index.html

 - Сейчас у тебя если открыть страничку на другой ОС (например Linux), есть шанс что твой текст будет криво отображаться. Для этого тебе нужно задать кодировку, добавив тег <meta charset="UTF-8"> в тег head

![Image](https://github.com/user-attachments/assets/857c9d56-71d0-4712-8261-4ca14ee81e16)

 - Классы пишутся с маленькой буквы

```html
<div class="Logo">
```

- У картиночек нет атрибута `alt`

```html
<img src="img/rogalik.jpg" class="img">
<img src="img/ulitka.jpg" class="img">
<img src="img/vatrushka.jpg" class="img">
<img src="img/bublik.jpg" class="img">
<img src="img/hachapuri.jfif" class="img">
```

### style.css

- Класс `Header` нигде не используется. Можно его снести)

```css
Header {
    display: flex;
    flex-direction: column;
    justify-content: center;
    width: 100%;
    gap: 40px;
    padding-top: 3%;
}
```
